### ISSUE TITLE
Does not work:

### ISSUE THREAD

**Issue by Parth** [avibryant/bazel-scala-example#11]
```
[~/Documents/test]: git clone git@github.com:avibryant/bazel-scala-example.git
Cloning into 'bazel-scala-example'...
cd bazremote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 126 (delta 0), reused 4 (delta 0), pack-reused 121
Receiving objects: 100% (126/126), 18.10 KiB | 1.51 MiB/s, done.
Resolving deltas: 100% (22/22), done.
```
```
[~/Documents/test, 2s]: cd bazel-scala-example
3rdparty                WORKSPACE               example-lib             intellij.bazelproject   tools
README.md               example-bin             example-maven           maven-dependencies.yaml
```
```
[~/Documents/test/bazel-scala-example, master]: bazel test example-lib:test
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/bazelbuild/rules_scala/archive/a89d44f7ef67d93dedfc9888630f48d7723516f7.zip) = e341dc30a397c77e6723a953d4a84539c050b49f163b4c50cf865c698ea598fe
DEBUG: Rule 'io_bazel_rules_scala' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "e341dc30a397c77e6723a953d4a84539c050b49f163b4c50cf865c698ea598fe"
DEBUG: Call stack for the definition of repository 'io_bazel_rules_scala' which is a http_archive (rule definition at /private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /Users/parth.mehrotra/Documents/test/bazel-scala-example/WORKSPACE:7:1
ERROR: /private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/io_bazel_rules_scala/scala/scala.bzl:111:13: cfg must be either 'host' or 'target'.
ERROR: /private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/io_bazel_rules_scala/scala/scala.bzl:125:22: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/io_bazel_rules_scala/scala/scala.bzl", line 125
                _common_attrs.update(_common_attrs_for_plugin_bootstr...)
        File "/private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/io_bazel_rules_scala/scala/scala.bzl", line 125, in _common_attrs.update
                _common_attrs_for_plugin_bootstrapping
global variable '_common_attrs_for_plugin_bootstrapping' is referenced before assignment.
ERROR: /private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/io_bazel_rules_scala/scala/scala.bzl:186:5: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/io_bazel_rules_scala/scala/scala.bzl", line 185
                _scala_library_for_plugin_bootstrapping_attrs.update(_common_attrs_for_plugin_bootstr...)
        File "/private/var/tmp/_bazel_parth.mehrotra/c0a6248eaf7cc9b8f927a829c682e756/external/io_bazel_rules_scala/scala/scala.bzl", line 186, in _scala_library_for_plugin_bootstrapping_attrs.update
                _common_attrs_for_plugin_bootstrapping
global variable '_common_attrs_for_plugin_bootstrapping' is referenced before assignment.
ERROR: error loading package '': Extension file 'scala/scala.bzl' has errors
ERROR: error loading package '': Extension file 'scala/scala.bzl' has errors
INFO: Elapsed time: 2.502s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by Parth** [comment]
Was because of a bazel version issue
